/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.File;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import model.MyNotepadModel;
import java.util.List;
/**
 *
 * @author HP
 */
public class MyNotepad extends javax.swing.JFrame {
    
    private MyNotepadModel myNotepadModel;
    /**
     * Creates new form MyNotepad
     */
    public MyNotepad() {
        this.myNotepadModel = new MyNotepadModel();
        initComponents();
        this.setSize(600, 600);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_footer = new javax.swing.JPanel();
        jLabel_path = new javax.swing.JLabel();
        jButton_open = new javax.swing.JButton();
        jButton_save = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Notepad");

        jPanel_footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_path.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_path.setText("New file");
        jLabel_path.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel_footer.add(jLabel_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 60));

        jButton_open.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_open.setText("Open");
        jButton_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_openActionPerformed(evt);
            }
        });
        jPanel_footer.add(jButton_open, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 30));

        jButton_save.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_save.setText("Save");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });
        jPanel_footer.add(jButton_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 90, 30));

        getContentPane().add(jPanel_footer, java.awt.BorderLayout.PAGE_END);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.setMinimumSize(new java.awt.Dimension(500, 500));
        jScrollPane.setViewportView(jTextArea);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_openActionPerformed
        JFileChooser jfc = new JFileChooser();
        int returnVal = jfc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION){
            File file = jfc.getSelectedFile();
            String fileName = file.getAbsolutePath();
            this.myNotepadModel.setTenFile(fileName);
            this.jLabel_path.setText(fileName);
            if (fileName.endsWith(".txt")){
                try {
                    List<String> allText = Files.readAllLines(file.toPath(), StandardCharsets.UTF_8);
                    String result = "";
                    for(String line : allText){
                        result += line;
                        result += "\n";
                    }
                    this.myNotepadModel.setNoiDung(result);
                    this.jTextArea.setText(result);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButton_openActionPerformed

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        if (this.myNotepadModel.getTenFile().length() > 0) {
            save( this.myNotepadModel.getTenFile());
        }
        else {
            JFileChooser jfc = new JFileChooser();
            int returnVal = jfc.showSaveDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION){
                try {
                    File file = jfc.getSelectedFile();
                    save(file.getCanonicalPath());
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButton_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyNotepad().setVisible(true);
            }
        });
    }
    
    public void save(String fileName){
        PrintWriter wr = null;
        try {
            wr = new PrintWriter(fileName, StandardCharsets.UTF_8);
            String data = this.jTextArea.getText();
            wr.print(data);
            wr.flush();
            wr.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_open;
    private javax.swing.JButton jButton_save;
    private javax.swing.JLabel jLabel_path;
    private javax.swing.JPanel jPanel_footer;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
