/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import model.NotepadModel;

/**
 *
 * @author HP
 */
public class NotepadView extends javax.swing.JFrame {
    private NotepadModel notepadModel;
    /**
     * Creates new form NotepadView
     */
    public NotepadView() {
        this.notepadModel = new NotepadModel();
        initComponents();
        this.setSize(600, 600);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_footer = new javax.swing.JPanel();
        jLabel_path = new javax.swing.JLabel();
        jButton_open = new javax.swing.JButton();
        jButton_save = new javax.swing.JButton();
        jScrollPane_text = new javax.swing.JScrollPane();
        jTextArea_text = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notepad");
        setSize(new java.awt.Dimension(600, 600));

        jPanel_footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_path.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_path.setText("New file");
        jLabel_path.setToolTipText("");
        jPanel_footer.add(jLabel_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 70));

        jButton_open.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_open.setText("OPEN");
        jButton_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_openActionPerformed(evt);
            }
        });
        jPanel_footer.add(jButton_open, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jButton_save.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_save.setText("SAVE");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });
        jPanel_footer.add(jButton_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        getContentPane().add(jPanel_footer, java.awt.BorderLayout.PAGE_END);

        jTextArea_text.setColumns(20);
        jTextArea_text.setRows(5);
        jTextArea_text.setMinimumSize(new java.awt.Dimension(600, 500));
        jScrollPane_text.setViewportView(jTextArea_text);

        getContentPane().add(jScrollPane_text, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_openActionPerformed
        JFileChooser jfc = new JFileChooser();
        int returnVal = jfc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION){
            File file = jfc.getSelectedFile();
            String fileName = file.getAbsolutePath();
            this.notepadModel.setFileName(fileName);
            this.jLabel_path.setText(fileName);
            if (fileName.endsWith(".txt")){
                try {
                    List<String> allText = Files.readAllLines(file.toPath(), StandardCharsets.UTF_8);
                    String result = "";
                    for(String line : allText) {
                        result += line;
                        result += "\n";
                    }
                    this.notepadModel.setContent(result);
                    this.jTextArea_text.setText(result);
                } catch (IOException ex) {
                    Logger.getLogger(NotepadView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton_openActionPerformed

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        if (this.notepadModel.getFileName().length() > 0) {
            save(this.notepadModel.getFileName());
        }
        else {
            JFileChooser jfc = new JFileChooser();
            int returnVal = jfc.showSaveDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION){
                File file = jfc.getSelectedFile();
                save(file.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_jButton_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotepadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotepadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotepadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotepadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotepadView().setVisible(true);
            }
        });
    }
    
    public void save(String fileName){
        PrintWriter wr = null;
        try {
            wr = new PrintWriter(fileName, StandardCharsets.UTF_8);
            String data = this.jTextArea_text.getText();
            wr.print(data);
            wr.flush();
            wr.close();
        } catch (IOException ex) {
            Logger.getLogger(NotepadView.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_open;
    private javax.swing.JButton jButton_save;
    private javax.swing.JLabel jLabel_path;
    private javax.swing.JPanel jPanel_footer;
    private javax.swing.JScrollPane jScrollPane_text;
    private javax.swing.JTextArea jTextArea_text;
    // End of variables declaration//GEN-END:variables
}
