/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.QLSVModel;

/**
 *
 * @author HP
 */
public class QLSVView extends javax.swing.JFrame {
    private QLSVModel qLSVModel;

    /**
     * Creates new form QLSVView
     */
    public QLSVView() {
        this.qLSVModel = new QLSVModel();
        initComponents();
        this.setSize(620, 650);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel_studentFilter = new javax.swing.JPanel();
        jLabel_birthPlace = new javax.swing.JLabel();
        jLabel_studentID = new javax.swing.JLabel();
        jTextField_studentID = new javax.swing.JTextField();
        jButton_filter = new javax.swing.JButton();
        jComboBox_birthPlace = new javax.swing.JComboBox<>();
        jPanel_listStudent = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable_student = new javax.swing.JTable();
        jPanel_studentInformation = new javax.swing.JPanel();
        jLabel_ID = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel_name = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jLabel_BirthPlace = new javax.swing.JLabel();
        jLabel_date = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton_male = new javax.swing.JRadioButton();
        jRadioButton_female = new javax.swing.JRadioButton();
        jLabel_subject1 = new javax.swing.JLabel();
        jTextField_subject1 = new javax.swing.JTextField();
        jLabel_subject2 = new javax.swing.JLabel();
        jTextField_subject2 = new javax.swing.JTextField();
        jLabel_subject3 = new javax.swing.JLabel();
        jTextField_subject3 = new javax.swing.JTextField();
        jTextField_date = new javax.swing.JTextField();
        jComboBox_BirthPlace = new javax.swing.JComboBox<>();
        jPanel_buttons = new javax.swing.JPanel();
        jButton_insert = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_edit = new javax.swing.JButton();
        jButton_ok = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu_file = new javax.swing.JMenu();
        jMenuItem_open = new javax.swing.JMenuItem();
        jMenuItem_close = new javax.swing.JMenuItem();
        jMenuItem_exit = new javax.swing.JMenuItem();
        jMenu_about = new javax.swing.JMenu();
        jMenuItem_aboutMe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project: Student");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_studentFilter.setBorder(javax.swing.BorderFactory.createTitledBorder("Student Filter"));

        jLabel_birthPlace.setText("BirthPlace");

        jLabel_studentID.setText("StudentID");

        jButton_filter.setText("Filter");

        jComboBox_birthPlace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang", "Bà Rịa - Vũng Tàu", "Bắc Giang", "Bắc Kạn", "Bạc Liêu", "Bắc Ninh", "Bến Tre", "Bình Định", "Bình Dương", "Bình Phước", "Bình Thuận", "Cà Mau", "Cần Thơ", "Cao Bằng", "Đà Nẵng", "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Nội", "Hà Tĩnh", "Hải Dương", "Hải Phòng", "Hậu Giang", "Hòa Bình", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lâm Đồng", "Lạng Sơn", "Lào Cai", "Long An", "Nam Định", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên Huế", "Tiền Giang", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái", "Hồ Chí Minh" }));
        jComboBox_birthPlace.setSelectedItem(null);
        jComboBox_birthPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_birthPlaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_studentFilterLayout = new javax.swing.GroupLayout(jPanel_studentFilter);
        jPanel_studentFilter.setLayout(jPanel_studentFilterLayout);
        jPanel_studentFilterLayout.setHorizontalGroup(
            jPanel_studentFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_studentFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_birthPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox_birthPlace, 0, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton_filter)
                .addGap(22, 22, 22))
        );
        jPanel_studentFilterLayout.setVerticalGroup(
            jPanel_studentFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_studentFilterLayout.createSequentialGroup()
                .addGroup(jPanel_studentFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_birthPlace)
                    .addComponent(jLabel_studentID)
                    .addComponent(jTextField_studentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_filter)
                    .addComponent(jComboBox_birthPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_studentFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        jPanel_listStudent.setBorder(javax.swing.BorderFactory.createTitledBorder("List Student"));

        jScrollPane.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jTable_student.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTable_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID", "Name", "Place", "Date", "Sex", "Subject 1", "Subject 2", "Subject 3"
            }
        ));
        jScrollPane.setViewportView(jTable_student);

        javax.swing.GroupLayout jPanel_listStudentLayout = new javax.swing.GroupLayout(jPanel_listStudent);
        jPanel_listStudent.setLayout(jPanel_listStudentLayout);
        jPanel_listStudentLayout.setHorizontalGroup(
            jPanel_listStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_listStudentLayout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_listStudentLayout.setVerticalGroup(
            jPanel_listStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_listStudentLayout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel_listStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 610, 220));

        jPanel_studentInformation.setBorder(javax.swing.BorderFactory.createTitledBorder("Student Information"));

        jLabel_ID.setText("ID");

        jLabel_name.setText("Name");

        jLabel_BirthPlace.setText("BirthPlace");

        jLabel_date.setText("Date");

        jLabel5.setText("Sex");

        buttonGroup.add(jRadioButton_male);
        jRadioButton_male.setText("M");

        buttonGroup.add(jRadioButton_female);
        jRadioButton_female.setText("F");
        jRadioButton_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_femaleActionPerformed(evt);
            }
        });

        jLabel_subject1.setText("Subject 1");

        jLabel_subject2.setText("Subject 2");

        jLabel_subject3.setText("Subject 3");

        jTextField_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_dateActionPerformed(evt);
            }
        });

        jComboBox_BirthPlace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang", "Bà Rịa - Vũng Tàu", "Bắc Giang", "Bắc Kạn", "Bạc Liêu", "Bắc Ninh", "Bến Tre", "Bình Định", "Bình Dương", "Bình Phước", "Bình Thuận", "Cà Mau", "Cần Thơ", "Cao Bằng", "Đà Nẵng", "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Nội", "Hà Tĩnh", "Hải Dương", "Hải Phòng", "Hậu Giang", "Hòa Bình", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lâm Đồng", "Lạng Sơn", "Lào Cai", "Long An", "Nam Định", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên Huế", "Tiền Giang", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái", "Hồ Chí Minh" }));
        jComboBox_BirthPlace.setSelectedItem(null);

        javax.swing.GroupLayout jPanel_studentInformationLayout = new javax.swing.GroupLayout(jPanel_studentInformation);
        jPanel_studentInformation.setLayout(jPanel_studentInformationLayout);
        jPanel_studentInformationLayout.setHorizontalGroup(
            jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_studentInformationLayout.createSequentialGroup()
                .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_studentInformationLayout.createSequentialGroup()
                        .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_studentInformationLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_studentInformationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_studentInformationLayout.createSequentialGroup()
                        .addComponent(jLabel_BirthPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_studentInformationLayout.createSequentialGroup()
                        .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_date, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_studentInformationLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel_subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_studentInformationLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_subject3)
                                    .addComponent(jLabel_subject2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_subject2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_subject3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_studentInformationLayout.createSequentialGroup()
                        .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_studentInformationLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jComboBox_BirthPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_studentInformationLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGap(23, 23, 23)
                        .addComponent(jRadioButton_male, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_female, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_studentInformationLayout.setVerticalGroup(
            jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_studentInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ID)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_subject1)
                    .addComponent(jTextField_subject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_name)
                    .addComponent(jLabel_subject2)
                    .addComponent(jTextField_subject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_BirthPlace)
                        .addComponent(jLabel_subject3)
                        .addComponent(jTextField_subject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox_BirthPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_studentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_date)
                    .addComponent(jTextField_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton_male)
                    .addComponent(jRadioButton_female))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_studentInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 600, 200));

        jButton_insert.setText("Insert");
        jButton_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertActionPerformed(evt);
            }
        });
        jPanel_buttons.add(jButton_insert);

        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });
        jPanel_buttons.add(jButton_delete);

        jButton_edit.setText("Edit");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });
        jPanel_buttons.add(jButton_edit);

        jButton_ok.setText("OK");
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });
        jPanel_buttons.add(jButton_ok);

        jButton_cancel.setText("Cancel");
        jPanel_buttons.add(jButton_cancel);

        getContentPane().add(jPanel_buttons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 600, -1));

        jMenu_file.setText("File");

        jMenuItem_open.setText("Open");
        jMenuItem_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_openActionPerformed(evt);
            }
        });
        jMenu_file.add(jMenuItem_open);

        jMenuItem_close.setText("Close");
        jMenu_file.add(jMenuItem_close);

        jMenuItem_exit.setText("Exit");
        jMenu_file.add(jMenuItem_exit);

        jMenuBar.add(jMenu_file);

        jMenu_about.setText("About");

        jMenuItem_aboutMe.setText("About me");
        jMenu_about.add(jMenuItem_aboutMe);

        jMenuBar.add(jMenu_about);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_openActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_openActionPerformed

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        this.refreshForm();
        this.qLSVModel.setLuaChon("Edit");
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jRadioButton_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_femaleActionPerformed

    private void jTextField_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_dateActionPerformed

    private void jComboBox_birthPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_birthPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_birthPlaceActionPerformed

    private void jButton_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertActionPerformed
        this.refreshForm();
        this.qLSVModel.setLuaChon("Insert");
        JOptionPane.showMessageDialog(this, "Bạn nhấn vào nút Insert", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_insertActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        this.refreshForm();
        this.qLSVModel.setLuaChon("Delete");
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        this.refreshForm();
        this.qLSVModel.setLuaChon("OK");
    }//GEN-LAST:event_jButton_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
                    new QLSVView().setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }
    
    public void refreshForm(){
        this.jTextField_ID.setText("");
        this.jTextField_name.setText("");
        this.jTextField_date.setText("");
        this.jTextField_subject1.setText("");
        this.jTextField_subject2.setText("");
        this.jTextField_subject3.setText("");
        this.jComboBox_BirthPlace.setSelectedItem(null);
        this.jRadioButton_male.setSelected(false);
        this.jRadioButton_female.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_filter;
    private javax.swing.JButton jButton_insert;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JComboBox<String> jComboBox_BirthPlace;
    private javax.swing.JComboBox<String> jComboBox_birthPlace;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_BirthPlace;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_birthPlace;
    private javax.swing.JLabel jLabel_date;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_studentID;
    private javax.swing.JLabel jLabel_subject1;
    private javax.swing.JLabel jLabel_subject2;
    private javax.swing.JLabel jLabel_subject3;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem_aboutMe;
    private javax.swing.JMenuItem jMenuItem_close;
    private javax.swing.JMenuItem jMenuItem_exit;
    private javax.swing.JMenuItem jMenuItem_open;
    private javax.swing.JMenu jMenu_about;
    private javax.swing.JMenu jMenu_file;
    private javax.swing.JPanel jPanel_buttons;
    private javax.swing.JPanel jPanel_listStudent;
    private javax.swing.JPanel jPanel_studentFilter;
    private javax.swing.JPanel jPanel_studentInformation;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JRadioButton jRadioButton_male;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable_student;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_date;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_studentID;
    private javax.swing.JTextField jTextField_subject1;
    private javax.swing.JTextField jTextField_subject2;
    private javax.swing.JTextField jTextField_subject3;
    // End of variables declaration//GEN-END:variables
}
